spring.application.name=billing_and_statement_generator
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql:5432/card_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD= }
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresqlDialect
spring.jpa.properties.hibernate.format_sql=true

#Logging
logging.level.com.example=DEBUG
logging.level.org.springframework.web=INFO